# Generated by Django 5.0.2 on 2024-03-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_frequency', models.CharField(max_length=10)),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_email', models.EmailField(max_length=254)),
                ('payment_method', models.CharField(max_length=20)),
            ],
        ),
    ]
