# Generated by Django 5.0.2 on 2024-03-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='comment',
            field=models.TextField(max_length=30),
        ),
    ]
