# Generated by Django 5.0.2 on 2024-03-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_contacts_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contacts',
        ),
    ]
