# Generated by Django 5.0.2 on 2024-03-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='con',
        ),
    ]
